#!/usr/bin/env bash
#
# This stag should be called from an API and it's output is the response
#
IFS=$'\n\t'
TOP_PID=$$

user_interrupt(){
	kill $BG_PID
	kill $TOP_PID
	hideSpinner
	exit 1
}

trap user_interrupt SIGINT
trap user_interrupt SIGTSTP

err_report(){
	echo "Error on line $1"
	kill $BG_PID
	kill $TOP_PID
	hideSpinner
	exit 1
}
trap 'err_report $LINENO' ERR

excludeFileTypes="\.(ico|properties|json|pro|ttf|dat|png|txt|jar|bat|jks|keystore)$"

answerColor="\033[35m"
titleColor="\033[37;44m"
perColorBelowOne="\033[31m"
perColorBelowTen="\033[33m"
perColorBelowFifty="\033[37m"
perColorBelowSeventyFive="\033[36m"
perColorUpToHundred="\033[32m"
reset="\033[0m"

jenkinsArea="$HOME/.jenkins/workspace"
indexFile="workspaces.txt"
cleanIndexFile="clean_workspaces.txt"
iosDir="emar-myvery_ios"
andDir="emar-myvery_android"

if [ -z "$1" ]; then
	echo -e "\033[97;101mNo branch supplied\033[0m"
	exit 1
fi

if [ -z "$2" ]; then
	echo -e "\033[97;101mNo OS supplied\033[0m"
	exit 1
fi

branch="$1"
ostype="$2"

cd "$jenkinsArea" || exit 1
sed 's/%2F/\//g' "$indexFile" > "$cleanIndexFile"

if [[ "$ostype" == "android" ]]; then
	cddir=$(cat clean_workspaces.txt | grep "emar_myvery_android/$branch" -A 1 | tail -n 1)
else
	cddir=$(cat clean_workspaces.txt | grep "emar_myvery_ios/$branch" -A 1 | tail -n 1)
fi

if [[ ! -z "$cddir" ]]; then
	if [[ "$ostype" == "android" ]]; then
		cd "$cddir@2/$andDir"
		jsonFile="$andDir.stag.json"
	elif [[ "$ostype" == "ios" ]]; then
		cd "$cddir@2/$iosDir"
		jsonFile="$iosDir.stag.json"
	else
		echo "ERROR"
	fi
fi

res=$(find . -name ".git" -maxdepth 1)
if [[ ! -z $res ]];then
	jsonOut="{"

	numberOfFiles=$(git ls-files | grep -vE "${excludeFileTypes}" | wc -l | sed 's/[[:space:]]//g')
	gitFiles=$(git ls-files | grep -vE "${excludeFileTypes}")
	numberOfExcludedFiles=$(git ls-files | grep -E "${excludeFileTypes}" | wc -l | sed 's/[[:space:]]//g' || echo -n "")
	numberOfCommittsTotal=$(git rev-list --count HEAD)

	jsonOut+="\"files\":\"$numberOfFiles\","
	jsonOut+="\"excludedFiles\":\"$numberOfExcludedFiles\","
	jsonOut+="\"committs\":\"$numberOfCommittsTotal\","
	jsonOut+="\"users\": ["

	linesOfCode=$(echo "$gitFiles" | while read f; do if [ -s $f ]; then git blame --line-porcelain $f | grep '^author ' | grep -v "Not Committed Yet"; fi; done | sort -f | uniq -ic | sort -rn | sed 's/author//g')

	declare -A emailsToCommits
	declare -A emailToNames
	declare -a justNumbers
	committSummary=$(git shortlog --summary --numbered --email)
	while IFS= read line
	do
		commits=$(echo "$line" | awk '{print $1}' | sed 's/[[:space:]]//g')
		author=$(echo "$line" | awk '{print $2}' | sed 's/[[:space:]]//g')
		fullName=$(echo "$line" | sed 's/<\(.*\)>//g' | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
		email=$(echo "$line" | sed 's/.*<\(.*\)>/\1/'| sed 's/[[:space:]]//g')
		email=$(echo "$email" | tr '[:upper:]' '[:lower:]')
		if [[ "${emailToNames[$email]+isset}" ]]; then
			curName=$(tr -d '[]' <<< "${emailToNames[$email]}")
			nextName="$curName:::$fullName"
			emailToNames+=(["$email"]=["$nextName"])
		else
			dealt=0
			for q in "${!emailToNames[@]}"; do
				standAloneNames=$(echo "${emailToNames[$q]}" | tr -d '[]' | sed 's/:::/, /g' )
				if [[ "$standAloneNames" =~ $fullName ]]; then
					curNames=$(tr -d '[]' <<< "${emailToNames[$q]}")
					nextName="$curNames:::$fullName"
					email="$q"
					emailToNames+=(["$email"]=["$nextName"])
					dealt=1
				fi
			done

			if [[ "$dealt" -eq 0 ]]; then
				emailToNames+=(["$email"]=["$fullName"])
			fi
		fi

		if [[ "${emailsToCommits[$email]+isset}" ]]; then
			current=$(tr -d '[]' <<< "${emailsToCommits[$email]}")
			next=$(( $current + $commits))
			emailsToCommits+=(["$email"]=["$next"])
		else
			emailsToCommits+=(["$email"]=["$commits"])
		fi
	done <<< "$committSummary"

	for i in "${!emailsToCommits[@]}"; do
		aa=$(echo "${emailsToCommits[$i]}" | tr -d '[]')
		justNumbers+=("$aa")
	done

	IFS=$'\n' sorted=($(sort -rn <<<"${justNumbers[*]}"))
	unset IFS

	totalLinesOfCodeInProject=0
	while read -r cc; do
		nn=$(echo "$cc" | awk '{print $1}')
		totalLinesOfCodeInProject=$(( "$totalLinesOfCodeInProject" + "$nn" ))
	done <<< "$linesOfCode"

	for t in "${sorted[@]}"; do
		for name in "${!emailToNames[@]}"; do

			# This gets the commits part and checks against the number sorted
			if [[ "${emailsToCommits[$name]}" == "[$t]" ]]; then

				cleanName=$(echo "${emailToNames[$name]}" | tr -d '[]' | sed 's/:::/, /g' )
				cleanCommitts=$(tr -d '[]' <<< "${emailsToCommits[$name]}")

				finalLines=0
				while read -r line; do
					justNameOfBlame=$(echo "$line" | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
					if [[ "$cleanName" =~ $justNameOfBlame ]]; then
						justNumOfLines=$(echo "$line" | awk '{print $1}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
						finalLines=$(( "$finalLines" + "$justNumOfLines" ))
					fi
				done <<< "$linesOfCode"
				

				singleName=$(echo "$cleanName" | cut -f1 -d",")
				perCommitts=$(echo "scale=4; ($cleanCommitts / $numberOfCommittsTotal)*100" | bc -l)
				if [[ ! "$perCommitts" == [0-9]* ]]; then perCommitts="0${perCommitts}"; fi
				perLines=$(echo "scale=4; ($finalLines / $totalLinesOfCodeInProject)*100" | bc -l)
				if [[ ! "$perLines" == [0-9]* ]]; then perLines="0${perLines}"; fi

				commColor="$perColorUpToHundred"
				if (( $(echo "$perCommitts < 1" | bc -l) )); then
					commColor="$perColorBelowOne"
				elif (( $(echo "$perCommitts < 10" | bc -l) )); then
					commColor="$perColorBelowTen"
				elif (( $(echo "$perCommitts < 50" | bc -l) )); then
					commColor="$perColorBelowFifty"
				elif (( $(echo "$perCommitts < 75" | bc -l) )); then
					commColor="$perColorBelowSeventyFive"
				else
					commColor="$perColorUpToHundred"
				fi

				lineColor="$perColorUpToHundred"
				if (( $(echo "$perLines < 1" | bc -l) )); then
					lineColor="$perColorBelowOne"
				elif (( $(echo "$perLines < 10" | bc -l) )); then
					lineColor="$perColorBelowTen"
				elif (( $(echo "$perLines < 50" | bc -l) )); then
					lineColor="$perColorBelowFifty"
				elif (( $(echo "$perLines < 75" | bc -l) )); then
					lineColor="$perColorBelowSeventyFive"
				else
					lineColor="$perColorUpToHundred"
				fi

				jsonOut+="{\"names\": [ \"$cleanName\" ],"
				jsonOut+="\"email\": \"$name\","
				jsonOut+="\"committs\": \"$cleanCommitts\","
				jsonOut+="\"committsPercent\": \"$perCommitts\","
				jsonOut+="\"lines\": \"$finalLines\","
				jsonOut+="\"linesPercent\": \"$perLines\"},"

				emailsToCommits[$name]="_"
			fi
		done
	done
	jsonOut=$(echo "$jsonOut" | sed 's/\(.*\),/\1/')
	jsonOut+="],"
	timestamp=$(date "+%H:%M %d-%m-%y")
	jsonOut+="\"time\":\"$timestamp\""
	jsonOut+="}"
	echo "$jsonOut" > "$jsonFile"
	echo "$jsonOut"
else
	echo -e "\033[97;101mNot a git repo!\033[0m"
	exit 1
fi
